# Generated by Django 6.0.6 on 2026-06-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nivel_permissao', models.CharField(choices=[('ESPECIAL', 'Especial'), ('COMUM', 'Comum')], default='COMUM', max_length=10, verbose_name='Nível de Permissão')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'core_tb_usuario',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Valvula',
            fields=[
                ('id_valvula', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('tipo_valvula', models.CharField(choices=[('ESFERA', 'Esfera'), ('GAVETA', 'Gaveta'), ('GLOBO', 'Globo'), ('RETENCAO', 'Retenção'), ('BORBOLETA', 'Borboleta'), ('GLOBO_CONTROLE', 'Globo Controle')], max_length=20, verbose_name='Tipo de Válvula')),
                ('norma', models.CharField(blank=True, max_length=50, verbose_name='Norma de Construção')),
                ('nbr', models.BooleanField(default=False, verbose_name='NBR 15827')),
                ('diametro', models.CharField(blank=True, max_length=10, verbose_name='Diâmetro')),
                ('classe', models.CharField(blank=True, max_length=20, verbose_name='Classe')),
                ('tipo_extremidade', models.CharField(blank=True, max_length=60, verbose_name='Tipo de Extremidade')),
                ('tipo_ranhura', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Ranhura')),
                ('tipo_montagem', models.CharField(blank=True, choices=[('TRUNNION', 'Trunnion'), ('FLUTUANTE', 'Flutuante')], max_length=50, null=True, verbose_name='Tipo de Montagem')),
                ('tipo_acionamento', models.CharField(blank=True, max_length=80, verbose_name='Tipo de Acionamento')),
                ('construcao_corpo', models.CharField(blank=True, choices=[('BI-PARTIDO', 'Bi-partido'), ('TRI-PARTIDO', 'Tri-partido')], max_length=50, null=True, verbose_name='Construção do Corpo')),
                ('dbb', models.BooleanField(default=False, verbose_name='DBB')),
                ('dib', models.CharField(blank=True, choices=[('DIB-1', 'DIB-1'), ('DIB-2', 'DIB-2'), ('N/A', 'N/A')], max_length=10, null=True, verbose_name='DIB')),
                ('valvula_alivio', models.BooleanField(default=False, verbose_name='Válvula de Alívio / Dreno')),
                ('dispositivo_antiestatico', models.BooleanField(default=False, verbose_name='Dispositivo Antiestático')),
                ('tipo_passagem', models.CharField(blank=True, choices=[('PLENA', 'Plena'), ('REDUZIDA', 'Reduzida')], max_length=20, null=True, verbose_name='Tipo de Passagem')),
                ('uso_geral', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uso Geral / Testada a Fogo')),
                ('baixa_emissao_fugitiva', models.BooleanField(default=False, verbose_name='Baixa Emissão Fugitiva')),
                ('certificacao_sil', models.CharField(blank=True, choices=[('SIL 1', 'SIL 1'), ('SIL 2', 'SIL 2'), ('SIL 3', 'SIL 3'), ('SIL 4', 'SIL 4')], max_length=10, null=True, verbose_name='Certificação SIL')),
                ('nace', models.CharField(blank=True, choices=[('MR0103 ISO 17495', 'MR0103 ISO 17495'), ('MR0175 ISO 15156', 'MR0175 ISO 15156'), ('N/A', 'N/A')], max_length=30, null=True, verbose_name='NACE')),
                ('tipo_castelo', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('EXTENDIDO', 'Extendido')], max_length=20, null=True, verbose_name='Tipo de Castelo')),
                ('juncao_corpo_castelo', models.CharField(blank=True, choices=[('APARAFUSADO', 'Aparafusado'), ('SOLDADO', 'Soldado'), ('ROSCADO', 'Roscado'), ('ROSCADO E SOLDADO', 'Roscado e Soldado')], max_length=30, null=True, verbose_name='Junção Corpo / Castelo')),
                ('categoria_borboleta', models.CharField(blank=True, choices=[('CATEGORIA A', 'Categoria A'), ('CATEGORIA B', 'Categoria B')], max_length=20, null=True, verbose_name='Categoria')),
                ('face_a_face', models.CharField(blank=True, choices=[('LUG', 'Lug'), ('WAFER', 'Wafer'), ('FLANGEADA PADRÃO CURTO', 'Flangeada Padrão Curto'), ('FLANGEADA PADRÃO LONGO', 'Flangeada Padrão Longo'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='Face a Face')),
                ('configuracao_disco', models.CharField(blank=True, choices=[('CONCÊNTRICA', 'Concêntrica'), ('BI-EXCÊNTRICA', 'Bi-Excêntrica'), ('TRI-EXCÊNTRICA', 'Tri-Excêntrica')], max_length=20, null=True, verbose_name='Configuração do Disco')),
                ('posicionador', models.CharField(blank=True, choices=[('ELETROPNEUMÁTICO 4–20 mA', 'Eletropneumático 4–20 mA'), ('ELETROPNEUMÁTICO 4–20 mA + HART', 'Eletropneumático 4–20 mA + HART'), ('FIELDBUS', 'Fieldbus'), ('PROFIBUS', 'Profibus')], max_length=50, null=True, verbose_name='Posicionador')),
                ('filtro', models.CharField(blank=True, choices=[('SIM, COM MANÔMETROS', 'Sim, com Manômetros'), ('SIM, SEM MANÔMETROS', 'Sim, sem Manômetros'), ('SIM, COM MAN. ELEMENTO FILTRANTE 5 μ', 'Sim, com Man. Elemento Filtrante 5 μ'), ('SIM, COM MAN. ELEMENTO FILTRANTE 5 μ CORPO ALUMÍNIO', 'Sim, com Man. Elemento Filtrante 5 μ Corpo Alumínio'), ('SIM, COM MAN. ELEMENTO FILTRANTE 5 μ CORPO AÇO INOX', 'Sim, com Man. Elemento Filtrante 5 μ Corpo Aço Inox')], max_length=80, null=True, verbose_name='Filtro')),
                ('indicador_posicao', models.BooleanField(default=False, verbose_name='Indicador de Posição')),
                ('tubing', models.CharField(blank=True, choices=[('INOX 316', 'Inox 316'), ('INOX 304', 'Inox 304'), ('COBRE', 'Cobre'), ('COBRE REVESTIDO', 'Cobre Revestido')], max_length=20, null=True, verbose_name='Tubing')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Válvula',
                'verbose_name_plural': 'Válvulas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComponentesInternos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inserto_rede', models.CharField(blank=True, default='', max_length=100, verbose_name='Inserto da Sede')),
                ('valvula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='core.valvula')),
            ],
            options={
                'verbose_name': 'Componente Interno',
                'verbose_name_plural': 'Componentes Internos',
            },
        ),
        migrations.CreateModel(
            name='Vedacao',
            fields=[
                ('id_vedacao', models.AutoField(primary_key=True, serialize=False)),
                ('vedacao_corpo_tampa', models.CharField(max_length=100, verbose_name='Vedação Corpo / Tampa')),
                ('valvula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vedacoes', to='core.valvula')),
            ],
            options={
                'verbose_name': 'Vedação',
                'verbose_name_plural': 'Vedações',
            },
        ),
        migrations.CreateModel(
            name='ValvulaMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_material', models.CharField(choices=[('CORPO_TAMPA', 'Corpo / Tampa'), ('OBTURADOR', 'Obturador'), ('SEDE', 'Sede / Porta Sede'), ('INSERTO_SEDE', 'Inserto da Sede'), ('HASTE', 'Haste'), ('MOLAS', 'Molas'), ('JUNTA', 'Junta'), ('GAXETA', 'Gaxeta'), ('PARAFUSOS', 'Parafusos'), ('PORCAS', 'Porcas')], max_length=20, verbose_name='Tipo de Material')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('valvula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='core.valvula')),
            ],
            options={
                'verbose_name': 'Material da Válvula',
                'verbose_name_plural': 'Materiais da Válvula',
                'unique_together': {('valvula', 'tipo_material')},
            },
        ),
    ]
