# Generated by Django 6.0.6 on 2026-06-12 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tb_usuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_usuario',
            name='token_verificacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token de Verificação'),
        ),
    ]
