# Generated by Django 6.0.6 on 2026-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tb_usuario_token_verificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_usuario',
            name='senha_alterada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última alteração de senha'),
        ),
        migrations.AddField(
            model_name='tb_usuario',
            name='token_expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Token'),
        ),
        migrations.AddField(
            model_name='tb_usuario',
            name='trocas_senha_hoje',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Trocas de senha hoje'),
        ),
        migrations.AddField(
            model_name='tb_usuario',
            name='ultima_data_troca',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última troca de senha'),
        ),
    ]
