# Generated by Django 4.2.30 on 2026-06-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tb_usuario_senha_alterada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='revestimento',
            field=models.CharField(blank=True, choices=[('DACROMETIZAÇÃO', 'Dacrometização'), ('ZINCO NÍQUEL', 'Zinco Níquel'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Revestimento'),
        ),
    ]
