# Generated by Django 6.0.6 on 2026-06-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_valvula_revestimento_alter_tb_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Projeto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='valvula',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valvulas', to='core.projeto', verbose_name='Projeto'),
        ),
    ]
