# Generated by Django 4.2.30 on 2026-06-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projeto_valvula_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='classe_pmt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PMT'),
        ),
    ]
