# Generated by Django 4.2.30 on 2026-06-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_valvula_classe_pmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='fabricante',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A')], default='N/A', max_length=80, null=True, verbose_name='Fabricante'),
        ),
    ]
