# Generated by Django 4.2.30 on 2026-06-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_valvula_fabricante'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoValvula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=500, unique=True, verbose_name='Chave no Storage')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo MIME')),
                ('tamanho', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('valvula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.valvula')),
            ],
            options={
                'verbose_name': 'Anexo da Válvula',
                'verbose_name_plural': 'Anexos da Válvula',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
