# Generated by Django 4.2.30 on 2026-06-23 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_anexovalvula'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valvulas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='tb_usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TentativaDuplicata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_valvula', models.CharField(choices=[('ESFERA', 'Esfera'), ('GAVETA', 'Gaveta'), ('GLOBO', 'Globo'), ('RETENCAO', 'Retenção'), ('BORBOLETA', 'Borboleta'), ('GLOBO_CONTROLE', 'Globo Controle')], max_length=20, verbose_name='Tipo de Válvula')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas_duplicata', to='core.projeto', verbose_name='Projeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas_duplicata', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('valvula_existente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas_duplicata', to='core.valvula', verbose_name='Válvula Existente')),
            ],
            options={
                'verbose_name': 'Tentativa de Duplicata',
                'verbose_name_plural': 'Tentativas de Duplicata',
                'ordering': ['-criado_em'],
            },
        ),
    ]
