# Generated by Django 4.2.30 on 2026-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_valvula_criado_por_alter_tb_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído')], default='ATIVO', max_length=10, verbose_name='Status'),
        ),
    ]
