# Generated by Django 4.2.30 on 2026-06-25 16:57

from django.db import migrations, models


def copiar_projeto_para_m2m(apps, schema_editor):
    """Preserva as associações existentes: copia o FK projeto para o novo M2M projetos."""
    Valvula = apps.get_model('core', 'Valvula')
    for v in Valvula.objects.exclude(projeto__isnull=True):
        v.projetos.add(v.projeto_id)


def reverter_m2m_para_projeto(apps, schema_editor):
    """Reverso: usa o primeiro projeto do M2M como FK projeto."""
    Valvula = apps.get_model('core', 'Valvula')
    for v in Valvula.objects.all():
        primeiro = v.projetos.first()
        if primeiro:
            v.projeto = primeiro
            v.save(update_fields=['projeto'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projeto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='valvulas', to='core.projeto', verbose_name='Projetos'),
        ),
        migrations.RunPython(copiar_projeto_para_m2m, reverter_m2m_para_projeto),
        migrations.RemoveField(
            model_name='valvula',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='tentativaduplicata',
            name='projeto',
        ),
        migrations.AlterField(
            model_name='valvula',
            name='certificacao_sil',
            field=models.CharField(blank=True, choices=[('SIL 1', 'SIL 1'), ('SIL 2', 'SIL 2'), ('SIL 3', 'SIL 3'), ('SIL 4', 'SIL 4'), ('N/A', 'N/A')], max_length=10, null=True, verbose_name='Certificação SIL'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='posicionador',
            field=models.CharField(blank=True, choices=[('ELETROPNEUMÁTICO 4–20 mA', 'Eletropneumático 4–20 mA'), ('FIELDBUS', 'Fieldbus'), ('PROFIBUS', 'Profibus')], max_length=50, null=True, verbose_name='Posicionador'),
        ),
    ]
