# Generated by Django 4.2.30 on 2026-06-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_projeto_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True, verbose_name='Chave do objeto')),
                ('data', models.BinaryField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Blob de Storage',
                'verbose_name_plural': 'Blobs de Storage',
            },
        ),
    ]
