# Generated by Django 4.2.30 on 2026-06-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_storageblob'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='qsl',
            field=models.CharField(blank=True, max_length=20, verbose_name='QSL'),
        ),
    ]
