# Generated by Django 4.2.30 on 2026-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_vedacao_vedacao_junta'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='anexo_nbr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Anexo NBR'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='dreno_vent_alivio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dreno / Vent / Alívio Externo'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='flange',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Flange'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='placa_identificacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa de Identificação'),
        ),
        migrations.AlterField(
            model_name='vedacao',
            name='vedacao_corpo_tampa',
            field=models.CharField(max_length=100, verbose_name='Vedação Sede / Tampa'),
        ),
    ]
