# Generated by Django 4.2.30 on 2026-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_caracteristicas_flange_placa_dreno_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvula',
            name='dreno_vent_alivio',
        ),
        migrations.AddField(
            model_name='valvula',
            name='alivio_externo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Alívio Externo'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='dreno',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dreno'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='vent',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Vent'),
        ),
    ]
