# Generated by Django 4.2.30 on 2026-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_split_dreno_vent_alivio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='alivio_externo',
            field=models.BooleanField(default=False, verbose_name='Alívio Externo'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='dreno',
            field=models.BooleanField(default=False, verbose_name='Dreno'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='vent',
            field=models.BooleanField(default=False, verbose_name='Vent'),
        ),
    ]
