# Generated by Django 4.2.30 on 2026-06-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dreno_vent_alivio_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvula',
            name='dbb',
        ),
        migrations.AlterField(
            model_name='valvula',
            name='dib',
            field=models.CharField(blank=True, choices=[('DBB', 'DBB'), ('DIB-1', 'DIB-1'), ('DIB-2', 'DIB-2'), ('N/A', 'N/A')], max_length=10, null=True, verbose_name='DIB'),
        ),
    ]
