# Generated by Django 4.2.30 on 2026-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_dbb_to_dib_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='fase',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='frequencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequência'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='posicao_falha',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('FECHADA', 'Fechada'), ('ULTIMA_POSICAO', 'Última Posição'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Posição em Caso de Falha'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='tensao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tensão'),
        ),
    ]
