# Generated by Django 4.2.30 on 2026-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_valvula_cor_alter_valvula_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='fabricante',
            field=models.CharField(blank=True, choices=[('DBV', 'DBV'), ('FDV', 'FDV'), ('YUANDA', 'Yuanda'), ('WINWAY/JITAI', 'Winway/Jitai'), ('NEWAY OIL EQUIPMENT', 'Neway Oil Equipment'), ('ARFLU', 'Arflu'), ('LJV', 'LJV'), ('NEWAY', 'Neway'), ('SHANXI', 'Shanxi'), ('JUNPIN', 'Junpin'), ('DEMBLA', 'Dembla'), ('N/A', 'N/A')], default='N/A', max_length=80, null=True, verbose_name='Fabricante'),
        ),
    ]
