# Generated by Django 4.2.30 on 2026-07-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_valvula_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='pintura',
            field=models.CharField(blank=True, choices=[('PADRÃO FABRICANTE', 'Padrão Fabricante'), ('ESPECIAL', 'Especial'), ('SEM PINTURA', 'Sem pintura')], max_length=30, null=True, verbose_name='Pintura'),
        ),
    ]
