# Generated by Django 4.2.30 on 2026-07-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_valvula_pintura'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='flange_acoplamento',
            field=models.CharField(blank=True, choices=[('F03', 'F03'), ('F04', 'F04'), ('F05', 'F05'), ('F07', 'F07'), ('F10', 'F10'), ('F12', 'F12'), ('F14', 'F14'), ('F16', 'F16'), ('F25', 'F25'), ('F30', 'F30'), ('F35', 'F35'), ('F40', 'F40'), ('F48', 'F48'), ('F60', 'F60')], max_length=10, null=True, verbose_name='Flange de Acoplamento ISO 5211'),
        ),
    ]
