# Generated by Django 4.2.30 on 2026-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_valvula_condicao_pintura_valvula_norma_pintura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='condicao_pintura',
            field=models.CharField(blank=True, choices=[('PADRÃO FABRICANTE', 'Padrão Fabricante'), ('N/A', 'N/A'), ('Condição 1', 'Condição 1'), ('Condição 2', 'Condição 2'), ('Condição 3', 'Condição 3'), ('Condição 4', 'Condição 4'), ('Condição 5', 'Condição 5'), ('Condição 6', 'Condição 6'), ('Condição 7', 'Condição 7'), ('Condição 8', 'Condição 8'), ('Zona Submersa', 'Zona Submersa'), ('Zona de Transição', 'Zona de Transição'), ('Zona Atmosférica', 'Zona Atmosférica'), ('Tipo I', 'Tipo I'), ('Tipo II', 'Tipo II'), ('Tipo III', 'Tipo III')], max_length=40, null=True, verbose_name='Condição de Pintura'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='norma_pintura',
            field=models.CharField(blank=True, choices=[('N-442', 'N-442'), ('N-1735', 'N-1735'), ('N-1374', 'N-1374'), ('N-2912', 'N-2912'), ('PADRÃO FABRICANTE', 'Padrão Fabricante'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Norma de Pintura'),
        ),
    ]
