# Generated by Django 4.2.30 on 2026-07-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_valvula_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='chave_fim_curso',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A')], max_length=20, null=True, verbose_name='Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='sensor_posicao',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A')], max_length=20, null=True, verbose_name='Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='valvula_escape_rapido',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A')], max_length=20, null=True, verbose_name='Válvula de Escape Rápido'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='valvula_lock_up',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A')], max_length=20, null=True, verbose_name='Válvula Lock-Up'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='valvula_solenoide',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A')], max_length=20, null=True, verbose_name='Válvula Solenoide'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='posicionador',
            field=models.CharField(blank=True, choices=[('4-20 mA', '4-20 mA'), ('PROTOCOLO HART', 'Protocolo Hart'), ('FIELDBUS', 'Fieldbus'), ('PROFIBUS', 'Profibus')], max_length=50, null=True, verbose_name='Posicionador'),
        ),
    ]
