# Generated by Django 6.0.6 on 2026-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_valvula_chave_fim_curso_valvula_sensor_posicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='posicionador',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('4-20 mA', '4-20 mA'), ('PROTOCOLO HART', 'Protocolo Hart'), ('FIELDBUS', 'Fieldbus'), ('PROFIBUS', 'Profibus')], max_length=50, null=True, verbose_name='Posicionador'),
        ),
    ]
