# Generated by Django 4.2.30 on 2026-07-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_valvula_controle_bloqueio_valvula_hot_disconnect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='funcao',
            field=models.CharField(choices=[('BLOQUEIO', 'Bloqueio'), ('CONTROLE', 'Controle')], default='BLOQUEIO', max_length=20, verbose_name='Função'),
        ),
    ]
