# Generated by Django 4.2.30 on 2026-07-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_valvula_ip_chave_fim_curso_valvula_ip_posicionador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='epl_chave_fim_curso',
            field=models.CharField(blank=True, choices=[('Ga', 'Ga'), ('Gb', 'Gb'), ('Gc', 'Gc')], max_length=10, null=True, verbose_name='EPL Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='epl_posicionador',
            field=models.CharField(blank=True, choices=[('Ga', 'Ga'), ('Gb', 'Gb'), ('Gc', 'Gc')], max_length=10, null=True, verbose_name='EPL Posicionador'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='epl_sensor_posicao',
            field=models.CharField(blank=True, choices=[('Ga', 'Ga'), ('Gb', 'Gb'), ('Gc', 'Gc')], max_length=10, null=True, verbose_name='EPL Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='epl_solenoide',
            field=models.CharField(blank=True, choices=[('Ga', 'Ga'), ('Gb', 'Gb'), ('Gc', 'Gc')], max_length=10, null=True, verbose_name='EPL Solenoid'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='ex_chave_fim_curso',
            field=models.CharField(blank=True, choices=[('Ex', 'Ex')], max_length=10, null=True, verbose_name='Ex Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='ex_posicionador',
            field=models.CharField(blank=True, choices=[('Ex', 'Ex')], max_length=10, null=True, verbose_name='Ex Posicionador'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='ex_sensor_posicao',
            field=models.CharField(blank=True, choices=[('Ex', 'Ex')], max_length=10, null=True, verbose_name='Ex Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='ex_solenoide',
            field=models.CharField(blank=True, choices=[('Ex', 'Ex')], max_length=10, null=True, verbose_name='Ex Solenoid'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='grupo_chave_fim_curso',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('IIC', 'IIC'), ('IIIA', 'IIIA'), ('IIIB', 'IIIB'), ('IIIC', 'IIIC')], max_length=10, null=True, verbose_name='Grupo Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='grupo_posicionador',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('IIC', 'IIC'), ('IIIA', 'IIIA'), ('IIIB', 'IIIB'), ('IIIC', 'IIIC')], max_length=10, null=True, verbose_name='Grupo Posicionador'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='grupo_sensor_posicao',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('IIC', 'IIC'), ('IIIA', 'IIIA'), ('IIIB', 'IIIB'), ('IIIC', 'IIIC')], max_length=10, null=True, verbose_name='Grupo Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='grupo_solenoide',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('IIC', 'IIC'), ('IIIA', 'IIIA'), ('IIIB', 'IIIB'), ('IIIC', 'IIIC')], max_length=10, null=True, verbose_name='Grupo Solenoid'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='protecao_chave_fim_curso',
            field=models.CharField(blank=True, choices=[('db', 'db'), ('db eb', 'db eb'), ('eb', 'eb'), ('ec', 'ec'), ('nA', 'nA'), ('tb', 'tb'), ('tc', 'tc'), ('pxb', 'pxb'), ('pyb', 'pyb'), ('pzc', 'pzc'), ('i', 'i')], max_length=10, null=True, verbose_name='Proteção Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='protecao_posicionador',
            field=models.CharField(blank=True, choices=[('db', 'db'), ('db eb', 'db eb'), ('eb', 'eb'), ('ec', 'ec'), ('nA', 'nA'), ('tb', 'tb'), ('tc', 'tc'), ('pxb', 'pxb'), ('pyb', 'pyb'), ('pzc', 'pzc'), ('i', 'i')], max_length=10, null=True, verbose_name='Proteção Posicionador'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='protecao_sensor_posicao',
            field=models.CharField(blank=True, choices=[('db', 'db'), ('db eb', 'db eb'), ('eb', 'eb'), ('ec', 'ec'), ('nA', 'nA'), ('tb', 'tb'), ('tc', 'tc'), ('pxb', 'pxb'), ('pyb', 'pyb'), ('pzc', 'pzc'), ('i', 'i')], max_length=10, null=True, verbose_name='Proteção Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='protecao_solenoide',
            field=models.CharField(blank=True, choices=[('db', 'db'), ('db eb', 'db eb'), ('eb', 'eb'), ('ec', 'ec'), ('nA', 'nA'), ('tb', 'tb'), ('tc', 'tc'), ('pxb', 'pxb'), ('pyb', 'pyb'), ('pzc', 'pzc'), ('i', 'i')], max_length=10, null=True, verbose_name='Proteção Solenoid'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='temp_chave_fim_curso',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], max_length=10, null=True, verbose_name='Classe Temp. Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='temp_posicionador',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], max_length=10, null=True, verbose_name='Classe Temp. Posicionador'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='temp_sensor_posicao',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], max_length=10, null=True, verbose_name='Classe Temp. Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='temp_solenoide',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], max_length=10, null=True, verbose_name='Classe Temp. Solenoid'),
        ),
    ]
