# Generated by Django 4.2.30 on 2026-07-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_valvula_epl_chave_fim_curso_valvula_epl_posicionador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='corrente_chave_fim_curso',
            field=models.CharField(blank=True, choices=[('2 A', '2 A'), ('3 A', '3 A'), ('4 A', '4 A'), ('5 A', '5 A'), ('6 A', '6 A'), ('7 A', '7 A'), ('8 A', '8 A'), ('9 A', '9 A'), ('10 A', '10 A'), ('11 A', '11 A'), ('12 A', '12 A'), ('13 A', '13 A'), ('14 A', '14 A'), ('15 A', '15 A'), ('16 A', '16 A'), ('17 A', '17 A'), ('18 A', '18 A'), ('19 A', '19 A'), ('20 A', '20 A'), ('21 A', '21 A'), ('22 A', '22 A'), ('23 A', '23 A'), ('24 A', '24 A'), ('25 A', '25 A'), ('26 A', '26 A'), ('27 A', '27 A'), ('28 A', '28 A'), ('29 A', '29 A'), ('30 A', '30 A'), ('31 A', '31 A'), ('32 A', '32 A'), ('33 A', '33 A'), ('34 A', '34 A'), ('35 A', '35 A'), ('36 A', '36 A'), ('37 A', '37 A'), ('38 A', '38 A'), ('39 A', '39 A'), ('40 A', '40 A'), ('41 A', '41 A'), ('42 A', '42 A'), ('43 A', '43 A'), ('44 A', '44 A'), ('45 A', '45 A'), ('46 A', '46 A'), ('47 A', '47 A'), ('48 A', '48 A'), ('49 A', '49 A'), ('50 A', '50 A')], max_length=10, null=True, verbose_name='Corrente Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='corrente_posicionador',
            field=models.CharField(blank=True, choices=[('2 A', '2 A'), ('3 A', '3 A'), ('4 A', '4 A'), ('5 A', '5 A'), ('6 A', '6 A'), ('7 A', '7 A'), ('8 A', '8 A'), ('9 A', '9 A'), ('10 A', '10 A'), ('11 A', '11 A'), ('12 A', '12 A'), ('13 A', '13 A'), ('14 A', '14 A'), ('15 A', '15 A'), ('16 A', '16 A'), ('17 A', '17 A'), ('18 A', '18 A'), ('19 A', '19 A'), ('20 A', '20 A'), ('21 A', '21 A'), ('22 A', '22 A'), ('23 A', '23 A'), ('24 A', '24 A'), ('25 A', '25 A'), ('26 A', '26 A'), ('27 A', '27 A'), ('28 A', '28 A'), ('29 A', '29 A'), ('30 A', '30 A'), ('31 A', '31 A'), ('32 A', '32 A'), ('33 A', '33 A'), ('34 A', '34 A'), ('35 A', '35 A'), ('36 A', '36 A'), ('37 A', '37 A'), ('38 A', '38 A'), ('39 A', '39 A'), ('40 A', '40 A'), ('41 A', '41 A'), ('42 A', '42 A'), ('43 A', '43 A'), ('44 A', '44 A'), ('45 A', '45 A'), ('46 A', '46 A'), ('47 A', '47 A'), ('48 A', '48 A'), ('49 A', '49 A'), ('50 A', '50 A')], max_length=10, null=True, verbose_name='Corrente Posicionador'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='corrente_sensor_posicao',
            field=models.CharField(blank=True, choices=[('2 A', '2 A'), ('3 A', '3 A'), ('4 A', '4 A'), ('5 A', '5 A'), ('6 A', '6 A'), ('7 A', '7 A'), ('8 A', '8 A'), ('9 A', '9 A'), ('10 A', '10 A'), ('11 A', '11 A'), ('12 A', '12 A'), ('13 A', '13 A'), ('14 A', '14 A'), ('15 A', '15 A'), ('16 A', '16 A'), ('17 A', '17 A'), ('18 A', '18 A'), ('19 A', '19 A'), ('20 A', '20 A'), ('21 A', '21 A'), ('22 A', '22 A'), ('23 A', '23 A'), ('24 A', '24 A'), ('25 A', '25 A'), ('26 A', '26 A'), ('27 A', '27 A'), ('28 A', '28 A'), ('29 A', '29 A'), ('30 A', '30 A'), ('31 A', '31 A'), ('32 A', '32 A'), ('33 A', '33 A'), ('34 A', '34 A'), ('35 A', '35 A'), ('36 A', '36 A'), ('37 A', '37 A'), ('38 A', '38 A'), ('39 A', '39 A'), ('40 A', '40 A'), ('41 A', '41 A'), ('42 A', '42 A'), ('43 A', '43 A'), ('44 A', '44 A'), ('45 A', '45 A'), ('46 A', '46 A'), ('47 A', '47 A'), ('48 A', '48 A'), ('49 A', '49 A'), ('50 A', '50 A')], max_length=10, null=True, verbose_name='Corrente Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='corrente_solenoide',
            field=models.CharField(blank=True, choices=[('2 A', '2 A'), ('3 A', '3 A'), ('4 A', '4 A'), ('5 A', '5 A'), ('6 A', '6 A'), ('7 A', '7 A'), ('8 A', '8 A'), ('9 A', '9 A'), ('10 A', '10 A'), ('11 A', '11 A'), ('12 A', '12 A'), ('13 A', '13 A'), ('14 A', '14 A'), ('15 A', '15 A'), ('16 A', '16 A'), ('17 A', '17 A'), ('18 A', '18 A'), ('19 A', '19 A'), ('20 A', '20 A'), ('21 A', '21 A'), ('22 A', '22 A'), ('23 A', '23 A'), ('24 A', '24 A'), ('25 A', '25 A'), ('26 A', '26 A'), ('27 A', '27 A'), ('28 A', '28 A'), ('29 A', '29 A'), ('30 A', '30 A'), ('31 A', '31 A'), ('32 A', '32 A'), ('33 A', '33 A'), ('34 A', '34 A'), ('35 A', '35 A'), ('36 A', '36 A'), ('37 A', '37 A'), ('38 A', '38 A'), ('39 A', '39 A'), ('40 A', '40 A'), ('41 A', '41 A'), ('42 A', '42 A'), ('43 A', '43 A'), ('44 A', '44 A'), ('45 A', '45 A'), ('46 A', '46 A'), ('47 A', '47 A'), ('48 A', '48 A'), ('49 A', '49 A'), ('50 A', '50 A')], max_length=10, null=True, verbose_name='Corrente Solenoid'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='potencia_chave_fim_curso',
            field=models.CharField(blank=True, choices=[('2 W', '2 W'), ('3 W', '3 W'), ('4 W', '4 W'), ('5 W', '5 W'), ('6 W', '6 W'), ('7 W', '7 W'), ('8 W', '8 W'), ('9 W', '9 W'), ('10 W', '10 W'), ('11 W', '11 W'), ('12 W', '12 W'), ('13 W', '13 W'), ('14 W', '14 W'), ('15 W', '15 W'), ('16 W', '16 W'), ('17 W', '17 W'), ('18 W', '18 W'), ('19 W', '19 W'), ('20 W', '20 W'), ('21 W', '21 W'), ('22 W', '22 W'), ('23 W', '23 W'), ('24 W', '24 W'), ('25 W', '25 W'), ('26 W', '26 W'), ('27 W', '27 W'), ('28 W', '28 W'), ('29 W', '29 W'), ('30 W', '30 W'), ('31 W', '31 W'), ('32 W', '32 W'), ('33 W', '33 W'), ('34 W', '34 W'), ('35 W', '35 W'), ('36 W', '36 W'), ('37 W', '37 W'), ('38 W', '38 W'), ('39 W', '39 W'), ('40 W', '40 W'), ('41 W', '41 W'), ('42 W', '42 W'), ('43 W', '43 W'), ('44 W', '44 W'), ('45 W', '45 W'), ('46 W', '46 W'), ('47 W', '47 W'), ('48 W', '48 W'), ('49 W', '49 W'), ('50 W', '50 W')], max_length=10, null=True, verbose_name='Potência Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='potencia_posicionador',
            field=models.CharField(blank=True, choices=[('2 W', '2 W'), ('3 W', '3 W'), ('4 W', '4 W'), ('5 W', '5 W'), ('6 W', '6 W'), ('7 W', '7 W'), ('8 W', '8 W'), ('9 W', '9 W'), ('10 W', '10 W'), ('11 W', '11 W'), ('12 W', '12 W'), ('13 W', '13 W'), ('14 W', '14 W'), ('15 W', '15 W'), ('16 W', '16 W'), ('17 W', '17 W'), ('18 W', '18 W'), ('19 W', '19 W'), ('20 W', '20 W'), ('21 W', '21 W'), ('22 W', '22 W'), ('23 W', '23 W'), ('24 W', '24 W'), ('25 W', '25 W'), ('26 W', '26 W'), ('27 W', '27 W'), ('28 W', '28 W'), ('29 W', '29 W'), ('30 W', '30 W'), ('31 W', '31 W'), ('32 W', '32 W'), ('33 W', '33 W'), ('34 W', '34 W'), ('35 W', '35 W'), ('36 W', '36 W'), ('37 W', '37 W'), ('38 W', '38 W'), ('39 W', '39 W'), ('40 W', '40 W'), ('41 W', '41 W'), ('42 W', '42 W'), ('43 W', '43 W'), ('44 W', '44 W'), ('45 W', '45 W'), ('46 W', '46 W'), ('47 W', '47 W'), ('48 W', '48 W'), ('49 W', '49 W'), ('50 W', '50 W')], max_length=10, null=True, verbose_name='Potência Posicionador'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='potencia_sensor_posicao',
            field=models.CharField(blank=True, choices=[('2 W', '2 W'), ('3 W', '3 W'), ('4 W', '4 W'), ('5 W', '5 W'), ('6 W', '6 W'), ('7 W', '7 W'), ('8 W', '8 W'), ('9 W', '9 W'), ('10 W', '10 W'), ('11 W', '11 W'), ('12 W', '12 W'), ('13 W', '13 W'), ('14 W', '14 W'), ('15 W', '15 W'), ('16 W', '16 W'), ('17 W', '17 W'), ('18 W', '18 W'), ('19 W', '19 W'), ('20 W', '20 W'), ('21 W', '21 W'), ('22 W', '22 W'), ('23 W', '23 W'), ('24 W', '24 W'), ('25 W', '25 W'), ('26 W', '26 W'), ('27 W', '27 W'), ('28 W', '28 W'), ('29 W', '29 W'), ('30 W', '30 W'), ('31 W', '31 W'), ('32 W', '32 W'), ('33 W', '33 W'), ('34 W', '34 W'), ('35 W', '35 W'), ('36 W', '36 W'), ('37 W', '37 W'), ('38 W', '38 W'), ('39 W', '39 W'), ('40 W', '40 W'), ('41 W', '41 W'), ('42 W', '42 W'), ('43 W', '43 W'), ('44 W', '44 W'), ('45 W', '45 W'), ('46 W', '46 W'), ('47 W', '47 W'), ('48 W', '48 W'), ('49 W', '49 W'), ('50 W', '50 W')], max_length=10, null=True, verbose_name='Potência Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='potencia_solenoide',
            field=models.CharField(blank=True, choices=[('2 W', '2 W'), ('3 W', '3 W'), ('4 W', '4 W'), ('5 W', '5 W'), ('6 W', '6 W'), ('7 W', '7 W'), ('8 W', '8 W'), ('9 W', '9 W'), ('10 W', '10 W'), ('11 W', '11 W'), ('12 W', '12 W'), ('13 W', '13 W'), ('14 W', '14 W'), ('15 W', '15 W'), ('16 W', '16 W'), ('17 W', '17 W'), ('18 W', '18 W'), ('19 W', '19 W'), ('20 W', '20 W'), ('21 W', '21 W'), ('22 W', '22 W'), ('23 W', '23 W'), ('24 W', '24 W'), ('25 W', '25 W'), ('26 W', '26 W'), ('27 W', '27 W'), ('28 W', '28 W'), ('29 W', '29 W'), ('30 W', '30 W'), ('31 W', '31 W'), ('32 W', '32 W'), ('33 W', '33 W'), ('34 W', '34 W'), ('35 W', '35 W'), ('36 W', '36 W'), ('37 W', '37 W'), ('38 W', '38 W'), ('39 W', '39 W'), ('40 W', '40 W'), ('41 W', '41 W'), ('42 W', '42 W'), ('43 W', '43 W'), ('44 W', '44 W'), ('45 W', '45 W'), ('46 W', '46 W'), ('47 W', '47 W'), ('48 W', '48 W'), ('49 W', '49 W'), ('50 W', '50 W')], max_length=10, null=True, verbose_name='Potência Solenoid'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='tensao_chave_fim_curso',
            field=models.CharField(blank=True, choices=[('12 VDC', '12 VDC'), ('12 VAC', '12 VAC'), ('24 VDC', '24 VDC'), ('24 VAC', '24 VAC'), ('127 VAC', '127 VAC'), ('120 VDC', '120 VDC'), ('220 VAC', '220 VAC')], max_length=10, null=True, verbose_name='Tensão Chave Fim de Curso'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='tensao_posicionador',
            field=models.CharField(blank=True, choices=[('12 VDC', '12 VDC'), ('12 VAC', '12 VAC'), ('24 VDC', '24 VDC'), ('24 VAC', '24 VAC'), ('127 VAC', '127 VAC'), ('120 VDC', '120 VDC'), ('220 VAC', '220 VAC')], max_length=10, null=True, verbose_name='Tensão Posicionador'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='tensao_sensor_posicao',
            field=models.CharField(blank=True, choices=[('12 VDC', '12 VDC'), ('12 VAC', '12 VAC'), ('24 VDC', '24 VDC'), ('24 VAC', '24 VAC'), ('127 VAC', '127 VAC'), ('120 VDC', '120 VDC'), ('220 VAC', '220 VAC')], max_length=10, null=True, verbose_name='Tensão Sensor de Posição'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='tensao_solenoide',
            field=models.CharField(blank=True, choices=[('12 VDC', '12 VDC'), ('12 VAC', '12 VAC'), ('24 VDC', '24 VDC'), ('24 VAC', '24 VAC'), ('127 VAC', '127 VAC'), ('120 VDC', '120 VDC'), ('220 VAC', '220 VAC')], max_length=10, null=True, verbose_name='Tensão Solenoid'),
        ),
    ]
