# Generated by Django 4.2.30 on 2026-07-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_valvula_corrente_chave_fim_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvula',
            name='controle_bloqueio',
        ),
    ]
