# Generated by Django 4.2.30 on 2026-07-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_valvula_condicao_pintura_atuador_valvula_cor_atuador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='valvula_escape_rapido',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('SIM', 'Sim')], max_length=20, null=True, verbose_name='Válvula de Escape Rápido'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='valvula_lock_up',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('SIM', 'Sim')], max_length=20, null=True, verbose_name='Válvula Lock-Up'),
        ),
    ]
