# Generated by Django 4.2.30 on 2026-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_valvula_iogp_alter_valvula_flange_acoplamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='iogp',
            field=models.CharField(blank=True, choices=[('IOGP AS-562', 'IOGP AS-562'), ('N/A', 'N/A')], default='IOGP AS-562', max_length=20, null=True, verbose_name='IOGP'),
        ),
    ]
