# Generated by Django 4.2.30 on 2026-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_valvula_iogp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='norma_pintura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Norma de Pintura'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='norma_pintura_atuador',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Norma de Pintura do Atuador'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='pintura',
            field=models.CharField(blank=True, choices=[('PADRÃO FABRICANTE', 'Padrão Fabricante'), ('SEM PINTURA', 'Sem pintura'), ('N-442', 'N-442'), ('N-1735', 'N-1735'), ('N-1374', 'N-1374'), ('N-2912', 'N-2912')], max_length=30, null=True, verbose_name='Pintura'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='pintura_atuador',
            field=models.CharField(blank=True, choices=[('PADRÃO FABRICANTE', 'Padrão Fabricante'), ('SEM PINTURA', 'Sem pintura'), ('N-442', 'N-442'), ('N-1735', 'N-1735'), ('N-1374', 'N-1374'), ('N-2912', 'N-2912')], max_length=30, null=True, verbose_name='Pintura do Atuador'),
        ),
    ]
