# Generated by Django 4.2.30 on 2026-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_valvula_norma_pintura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='fase',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20, null=True, verbose_name='Fase'),
        ),
    ]
