# Generated by Django 4.2.30 on 2026-07-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_valvula_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='chave_fim_curso',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('SIM', 'Sim')], max_length=20, null=True, verbose_name='Chave Fim de Curso'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='sensor_posicao',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('SIM', 'Sim')], max_length=20, null=True, verbose_name='Sensor de Posição'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='valvula_solenoide',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('SIM', 'Sim')], max_length=20, null=True, verbose_name='Válvula Solenoide'),
        ),
    ]
