# Generated by Django 4.2.30 on 2026-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_tb_usuario_groups_tb_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoFlange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100, unique=True, verbose_name='Valor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Norma de Flange',
                'verbose_name_plural': 'Normas de Flange',
                'ordering': ['ordem', 'valor'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpcaoPlacaIdentificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100, unique=True, verbose_name='Valor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Placa de Identificação',
                'verbose_name_plural': 'Placas de Identificação',
                'ordering': ['ordem', 'valor'],
                'abstract': False,
            },
        ),
    ]
