# Generated by Django 4.2.30 on 2026-07-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_seed_opcoes_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='marca_atuador',
            field=models.CharField(blank=True, choices=[('ROTORK', 'Rotork'), ('LT', 'LT'), ('BIPPI', 'Bippi'), ('PADRÃO FABRICANTE', 'Padrão Fabricante')], max_length=30, null=True, verbose_name='Marca do Atuador'),
        ),
    ]
