# Generated by Django 4.2.30 on 2026-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_valvula_marca_atuador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('55', '55'), ('60', '60')], max_length=20, null=True, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='tensao',
            field=models.CharField(blank=True, choices=[('120', '120'), ('127', '127'), ('220', '220'), ('380', '380'), ('440', '440')], max_length=20, null=True, verbose_name='Tensão'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='valvula_lock_up',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('2 VIAS', '2 Vias'), ('3 VIAS', '3 Vias')], max_length=20, null=True, verbose_name='Válvula Lock-Up'),
        ),
    ]
