# Generated by Django 4.2.30 on 2026-07-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_seed_opcoes_flange_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='marca_atuador',
            field=models.CharField(blank=True, choices=[('ROTORK', 'Rotork'), ('LT', 'LT'), ('BIFFI', 'Biffi'), ('EXTRA', 'Extra'), ('ZHONGHUAN', 'Zhonghuan'), ('PADRÃO FABRICANTE', 'Padrão Fabricante')], max_length=30, null=True, verbose_name='Marca do Atuador'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='valvula_escape_rapido',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('2 VIAS', '2 Vias'), ('3 VIAS', '3 Vias')], max_length=20, null=True, verbose_name='Válvula de Escape Rápido'),
        ),
        migrations.AlterField(
            model_name='valvulamaterial',
            name='tipo_material',
            field=models.CharField(choices=[('CORPO_TAMPA', 'Corpo / Tampa'), ('OBTURADOR', 'Obturador'), ('SEDE', 'Sede / Porta Sede'), ('INSERTO_SEDE', 'Inserto da Sede'), ('HASTE', 'Haste'), ('MOLAS', 'Molas'), ('JUNTA', 'Categoria Materiais'), ('MATERIAL_JUNTA', 'Materiais da Junta'), ('GAXETA', 'Gaxeta'), ('PARAFUSOS', 'Parafusos'), ('PORCAS', 'Porcas')], max_length=20, verbose_name='Tipo de Material'),
        ),
    ]
