# Generated by Django 4.2.30 on 2026-07-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_valvula_marca_atuador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvulamaterial',
            name='tipo_material',
            field=models.CharField(choices=[('CORPO_TAMPA', 'Corpo / Tampa'), ('OBTURADOR', 'Obturador'), ('SEDE', 'Sede / Porta Sede'), ('INSERTO_SEDE', 'Inserto da Sede'), ('HASTE', 'Haste'), ('MOLAS', 'Molas'), ('JUNTA', 'Categoria Junta'), ('MATERIAL_JUNTA', 'Materiais da Junta'), ('GAXETA', 'Gaxeta'), ('PARAFUSOS', 'Parafusos'), ('PORCAS', 'Porcas')], max_length=20, verbose_name='Tipo de Material'),
        ),
    ]
