# Generated by Django 4.2.30 on 2026-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_valvulamaterial_tipo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='contra_peso',
            field=models.BooleanField(default=False, verbose_name='Contrapeso'),
        ),
    ]
