# Generated by Django 4.2.30 on 2026-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_valvula_contra_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='configuracao_corpo_retencao',
            field=models.CharField(blank=True, choices=[('ANGULAR', 'Angular'), ('RETO', 'Reto')], max_length=10, null=True, verbose_name='Configuração do Corpo'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='orientacao_instalacao',
            field=models.CharField(blank=True, choices=[('HORIZONTAL', 'Horizontal'), ('VERTICAL', 'Vertical')], max_length=10, null=True, verbose_name='Orientação de Instalação'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='tipo_retencao',
            field=models.CharField(blank=True, choices=[('PISTAO', 'Pistão'), ('ESFERA', 'Esfera'), ('DISCO', 'Disco')], max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
