# Generated by Django 4.2.30 on 2026-07-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_valvula_configuracao_corpo_retencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvula',
            name='face_a_face',
            field=models.CharField(blank=True, choices=[('LUG', 'Lug'), ('WAFER', 'Wafer'), ('FLANGEADA PADRÃO CURTO', 'Flangeada Padrão Curto'), ('FLANGEADA PADRÃO LONGO', 'Flangeada Padrão Longo'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='Tipo de Conexão'),
        ),
    ]
