# Generated by Django 4.2.30 on 2026-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_valvula_face_a_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='categoria_594',
            field=models.CharField(blank=True, choices=[('TIPO A', 'Tipo A'), ('TIPO B', 'Tipo B')], max_length=10, null=True, verbose_name='Categoria (API 594)'),
        ),
    ]
